title: "Apuntes del Estado"
description: "Resúmenes y apuntes de Adm. Pública"

# Tema remoto (obligatorio para GitHub Pages)
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# Configuración del tema
just_the_docs:
  search_enabled: true
  enable_heading_ids: true
