title: "fuliculi222 (FÃ©lix)"
description: "Apuntes"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

toc:
  min_level: 2
  max_level: 4
  list_class: "toc"
  heading: "Contenido"

markdown: kramdown
kramdown:
  input: GFM
